# Generated by Django 4.1.4 on 2023-04-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_estimates_estimateitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='terms_conditions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
