# Generated by Django 4.1.4 on 2023-04-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_estimates_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
