# Generated by Django 4.1.4 on 2023-04-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_estimates_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='interstate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='intrastate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
