# Generated by Django 4.1.4 on 2023-04-26 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0011_additem_interstate_additem_intrastate'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=100, null=True)),
                ('customerType', models.CharField(blank=True, max_length=100, null=True)),
                ('companyName', models.CharField(blank=True, max_length=100, null=True)),
                ('customerEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('customerWorkPhone', models.CharField(blank=True, max_length=100, null=True)),
                ('customerMobile', models.CharField(blank=True, max_length=100, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTTreatment', models.CharField(blank=True, max_length=100, null=True)),
                ('placeofsupply', models.CharField(blank=True, max_length=100, null=True)),
                ('Taxpreference', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('OpeningBalance', models.IntegerField(blank=True, null=True)),
                ('PaymentTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('PriceList', models.CharField(blank=True, max_length=100, null=True)),
                ('PortalLanguage', models.CharField(blank=True, max_length=100, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('Attention', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('Address1', models.CharField(blank=True, max_length=100, null=True)),
                ('Address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('CPsalutation', models.CharField(blank=True, max_length=100, null=True)),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('CPemail', models.CharField(blank=True, max_length=100, null=True)),
                ('CPphone', models.CharField(blank=True, max_length=100, null=True)),
                ('CPmobile', models.CharField(blank=True, max_length=100, null=True)),
                ('CPskype', models.CharField(blank=True, max_length=100, null=True)),
                ('CPdesignation', models.CharField(blank=True, max_length=100, null=True)),
                ('CPdepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
