# Generated by Django 4.1.4 on 2023-04-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='tax_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
