# Generated by Django 4.1.4 on 2023-04-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_estimates_tax_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimates',
            old_name='tax_amount',
            new_name='tax_percentage',
        ),
    ]
