# Generated by Django 4.1.4 on 2023-04-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_rename_tax_amount_estimates_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitems',
            old_name='tax',
            new_name='tax_percentage',
        ),
        migrations.RenameField(
            model_name='estimates',
            old_name='tax_percentage',
            new_name='tax_amount',
        ),
    ]
