# Generated by Django 4.1.4 on 2023-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_rename_tax_estimateitems_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='attachment',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
