# Generated by Django 4.1.4 on 2023-05-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_customer_invoice_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
