# Generated by Django 4.1.4 on 2023-05-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0020_alter_estimates_igst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
