# Generated by Django 4.1.4 on 2023-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0023_alter_invoice_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='inv',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='invoice_item',
        ),
    ]
