# Generated by Django 4.1.4 on 2023-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_invoice_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
